cmake_minimum_required(VERSION 3.21)

project(AlgorithmLibrary LANGUAGES CXX C)
if (${MSVC})
    message(STATUS "Generator: MSVC")
    message(STATUS "  \${MSVC_TOOLSET_VERSION} = " ${MSVC_TOOLSET_VERSION})
    message(STATUS "  \${MSVC_VERSION} = " ${MSVC_VERSION})
else (${UNIX})
    message(STATUS "UNIX = " ${UNIX})
endif ()
if (${WIN32})
    message(STATUS "WIN32 = " ${WIN32})
endif ()
message(STATUS "CMAKE_SYSTEM_NAME = " ${CMAKE_SYSTEM_NAME})
# 设定 C++ 标准
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if(CMAKE_CL_64)
    set(CURRENT_PLATFORM "x64")
    message(STATUS "Current Platform is ${CURRENT_PLATFORM}")
else (CMAKE_CL_64)
    set(CURRENT_PLATFORM "x86")
    message(STATUS "Current Platform is ${CURRENT_PLATFORM}")
endif (CMAKE_CL_64)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")
include(VersionInfo)
include(MSVCToolchainPaths)
add_subdirectory(AlgorithmLibrary)
#add_subdirectory(AlgorithmTest)
#add_subdirectory(AlgorithmCTypeTest)
add_subdirectory(AlgorithmDemo)
